spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/save-the-children-users
    username: postgres
    password: GW873S&%
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  sql:
    init:
      mode: always
debug: false
